{{ if .Values.configmaps.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.configmapname }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob (printf "%s/*" .Values.configmaps.configmapsfiles ) ).AsConfig . ) | indent 2 }}
{{ end }}
